### ISSUE TITLE
License Violation

### ISSUE THREAD

**Issue by dashezup** [TamilBots/TamilVcBot#4]
This project (TamilVcBot) is based on my [tgvc-userbot](https://github.com/callsmusic/tgvc-userbot/tree/smart-plugins) project (old source code, smart-plugins branch).

tgvc-userbot is licensed under [AGPL-3.0](https://github.com/callsmusic/tgvc-userbot/blob/smart-plugins/LICENSE#L632), the current LICENSE text of TamilVcBot is [GPL-3.0](https://github.com/TamilBots/TamilVcBot/blob/3f456185f13f461f44a8f52f1eba663fa71fbafd/LICENSE), it violates the AGPL-3.0 license to redistribute with GPL-3.0 license.

You should change the LICENSE to AGPL-3.0 (or any later version).

**Comment by TamilBots** [comment]
OKAY

**Comment by TamilBots** [comment]
OKAY
